language: ruby
rvm:
    - 2.1.2
branches:
    only:
        - master
script:
    - bundle exec rake db:test:prepare
    - RAILS_ENV=test bundle exec rake db:create --trace
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rspec spec/
services:
    - elasticsearch
before_install:
    - sudo apt-get install -qq openjdk-6-jre
before_script:
    - cp config/database.travis.yml config/database.yml
    - psql -c 'create database trado_test_db' -U postgres
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install bower -g
    - bower install