development:
  adapter: postgresql
  encoding: unicode
  database: trado_dev
  pool: 5
  username: tomdallimore
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: trado_test
  pool: 5
  username: tomdallimore
  password: 


production:
  adapter: postgresql
  encoding: unicode
  database: trado
  pool: 5
  username: postgres
  password: admin
  # adapter: mysql2
  # encoding: utf8
  # database: travis_db
  # host: localhost
  # pool: 30
  # username:
  # password:
  # socket: /var/run/mysqld/mysqld.sock
