development:
    global_host: localhost:3000
    secret_token: wkqndbdnwdjnq
    secret_key_base: wkqndbdnwdjnq
    mailer_server: smtp.example.com
    mailer_port: 587
    mailer_domain: localhost:3000
    mailer_user_name: me@example.com
    mailer_password: wkqndbdnwdjnq
    aws_s3_id: wkqndbdnwdjnq
    aws_s3_key: wkqndbdnwdjnq
    aws_s3_bucket: example-bucket
    aws_s3_region: eu-region-1
    aws_cloudfront_host_carrierwave: http://cdn1.example.com
    aws_cloudfront_host_app: http://cdn%d.example.com
    aws_cloudfront_prefix: /assets
    sitemap_host: http://www.example.com
    rollbar_access_token: wkqndbdnwdjnq
    email_root: http://cdn0.example.com/email