development:
    global_host: localhost:3000
    secret_token: 8adbe40608f75dbaf0e53bd377613df08d1c208a55f24172007bb7f3243aa5ed220a582a12184b3ff8bced3c2d1f5e83205994743b936d57d1b6a63d7b8ec48a
    secret_key_base: d9ac75015119e7603233e7b59c3b2af7562b8c014033739f9b4e42a365aa7a44d8c74525a2b6861f0c1cb9a6ec6437512fec76dbe7c646dccebf8b9e9bc05d51
    mailer_server: smtp.example.com
    mailer_port: 587
    mailer_domain: localhost:3000
    mailer_user_name: me@example.com
    mailer_password: wkqndbdnwdjnq
    aws_s3_id: wkqndbdnwdjnq
    aws_s3_key: wkqndbdnwdjnq
    aws_s3_bucket: example-bucket
    aws_s3_region: eu-region-1
    aws_cloudfront_host_carrierwave: http://cdn1.example.com
    aws_cloudfront_host_app: http://cdn%d.example.com
    aws_cloudfront_prefix: /assets
    sitemap_host: http://www.example.com
    rollbar_access_token: wkqndbdnwdjnq
    email_root: http://cdn0.example.com/email
test:
    global_host: localhost:3000
    secret_token: 8adbe40608f75dbaf0e53bd377613df08d1c208a55f24172007bb7f3243aa5ed220a582a12184b3ff8bced3c2d1f5e83205994743b936d57d1b6a63d7b8ec48a
    secret_key_base: d9ac75015119e7603233e7b59c3b2af7562b8c014033739f9b4e42a365aa7a44d8c74525a2b6861f0c1cb9a6ec6437512fec76dbe7c646dccebf8b9e9bc05d51
    mailer_server: smtp.example.com
    mailer_port: 587
    mailer_domain: localhost:3000
    mailer_user_name: me@example.com
    mailer_password: wkqndbdnwdjnq
    aws_s3_id: wkqndbdnwdjnq
    aws_s3_key: wkqndbdnwdjnq
    aws_s3_bucket: example-bucket
    aws_s3_region: eu-region-1
    aws_cloudfront_host_carrierwave: http://cdn1.example.com
    aws_cloudfront_host_app: http://cdn%d.example.com
    aws_cloudfront_prefix: /assets
    sitemap_host: http://www.example.com
    rollbar_access_token: wkqndbdnwdjnq
    email_root: http://cdn0.example.com/email